import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import colors from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.secondary,
    alignItems: 'center',
  },
  containerInputText: {
    flexDirection: 'row',
    borderRadius: 15,
    borderWidth: 2,
    width: wp('75%'),
    height: hp('5%'),
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  InputText: {
    width: wp('55%'),
    height: hp('5%'),
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerNoneCenter: {
    width: wp('100%'),
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  containerPageLogin: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    backgroundColor: colors.secondary,
  },
  containerNoneRowBottom: {
    position: 'absolute',
    flexDirection: 'row',
    bottom: hp('5%'),
    alignItems: 'center',
  },
  containerNoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  containerTopBar: {
    width: wp('100%'),
    height: hp('7.5%'),
    backgroundColor: colors.darkGray,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  containerTopBarComponent1: {flex: 1, alignItems: 'center'},
  containerTopBarComponent2: {flex: 3, alignItems: 'center'},
  containerTopBarComponent3: {flex: 1, alignItems: 'center'},
  containerComponentLeftRow: {
    flexDirection: 'row',
    // alignItems: 'center',
  },
  textWhite: {
    color: colors.white,
  },
  textBlack: {
    color: colors.black,
    fontWeight: 'bold',
    fontSize: wp('5%'),
  },
  textBlackMedium: {
    color: colors.black,
  },
  textBoldWhite: {
    color: colors.white,
    fontWeight: 'bold',
  },
  textBoldWhiteMedium: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: wp('5%'),
  },
  textBoldWhiteLarge: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: wp('6%'),
  },
  textBoldBlue: {
    color: colors.blue,
    fontWeight: 'bold',
  },
  textBoldBlueLarge: {
    color: colors.blue,
    fontWeight: 'bold',
    fontSize: wp('6%'),
  },
  textBoldRed: {
    color: colors.redDark,
    fontWeight: 'bold',
  },
  buttonOutlineSmall: {
    borderRadius: 15,
    borderWidth: 2,
    width: wp('20%'),
    height: hp('3.5%'),
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
  },
  buttonOutlineMedium: {
    borderRadius: 15,
    borderWidth: 2,
    width: wp('30%'),
    height: hp('4%'),
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
  },
  buttonSolidMedium: {
    borderRadius: 15,
    backgroundColor: colors.blue,
    width: wp('30%'),
    height: hp('4%'),
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
  },
  buttonSolidMediumSecondary: {
    borderRadius: 15,
    backgroundColor: colors.darkGray,
    width: wp('30%'),
    height: hp('4%'),
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
  },
  buttonSolid: {
    borderRadius: 15,
    width: wp('75%'),
    height: hp('5%'),
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
  },
  buttonSolidCustom: (color, width, height, borderRadius) => ({
    borderRadius: borderRadius,
    width: width,
    height: height,
    backgroundColor: color,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
  }),
  listRoomChat: {
    flexDirection: 'row',
    width: wp('100%'),
    borderBottomWidth: 1,
    height: hp('9%'),
    backgroundColor: colors.darkGray,
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 5,
  },
  buttonSolidSecondary: {
    borderRadius: 15,
    width: wp('75%'),
    height: hp('5%'),
    backgroundColor: colors.darkGray,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
  },
  containerAddPhotoIcon: {
    position: 'absolute',
    height: wp('7%'),
    width: wp('7%'),
    bottom: 0,
    right: 0,
    backgroundColor: colors.black,
    borderRadius: 50,
    justifyContent: 'center',
  },
});
